// HTTP status codes as defined by https://httpwg.org/specs/rfc9110.html#overview.of.status.codes

const STATUS_CONTINUE = 100
const STATUS_SWITCHING_PROTOCOLS = 101
const STATUS_OK = 200
const STATUS_CREATED = 201
const STATUS_ACCEPTED = 202
const STATUS_NON_AUTHORITATIVE = 203
const STATUS_NO_CONTENT = 204
const STATUS_RESET_CONTENT = 205
const STATUS_PARTIAL_CONTENT = 206
const STATUS_MULTIPLE_CHOICES = 300
const STATUS_MOVED_PERMANENTLY = 301
const STATUS_FOUND = 302
const STATUS_SEE_OTHER = 303
const STATUS_NOT_MODIFIED = 304
const STATUS_PROXY = 305
const STATUS_UNUSED = 306
const STATUS_TEMPORARY_REDIRECT = 307
const STATUS_PERMANENT_REDIRECT = 308
const STATUS_BAD_REQUEST = 400
const STATUS_UNAUTHORIZED = 401
const STATUS_PAYMENT_REQUIRED = 402
const STATUS_FORBIDDEN = 403
const STATUS_NOT_FOUND = 404
const STATUS_METHOD_NOT_ALLOWED = 405
const STATUS_NOT_ACCEPTABLE = 406
const STATUS_PROXY_AUTHENTICATION_REQUIRED = 407
const STATUS_REQUEST_TIMEOUT = 408
const STATUS_CONFLICT = 409
const STATUS_GONE = 410
const STATUS_LENGTH_REQUIRED = 411
const STATUS_PRECONDITION_FAILED = 412
const STATUS_CONTENT_TOO_LARGE = 413
const STATUS_URI_TOO_LONG = 414
const STATUS_UNSUPPORTED_MEDIA_TYPE = 415
const STATUS_RANGE_NOT_SPECIFIED = 416
const STATUS_EXPECTATION_FAILED = 417
const STATUS_BAD_UNUSED = 418
const STATUS_MISDIRECTED_REQUEST = 421
const STATUS_UNPROCESSABLE_CONTENT = 422
const STATUS_UPGRADE_REQUIRED = 426
const STATUS_INTERNAL_SERVER_ERROR = 500
const STATUS_NOT_IMPLEMENTED = 501
const STATUS_BAD_GATEWAY = 502
const STATUS_SERVICE_UNVAILABLE = 503
const STATUS_GATEWAY_TIMEOUT = 504
const STATUS_HTTP_VERSION_NOT_SUPPORTED = 505

export {
  STATUS_ACCEPTED,
  STATUS_BAD_GATEWAY,
  STATUS_BAD_REQUEST,
  STATUS_BAD_UNUSED,
  STATUS_CONFLICT,
  STATUS_CONTENT_TOO_LARGE,
  STATUS_CONTINUE,
  STATUS_CREATED,
  STATUS_EXPECTATION_FAILED,
  STATUS_FORBIDDEN,
  STATUS_FOUND,
  STATUS_GATEWAY_TIMEOUT,
  STATUS_GONE,
  STATUS_HTTP_VERSION_NOT_SUPPORTED,
  STATUS_INTERNAL_SERVER_ERROR,
  STATUS_LENGTH_REQUIRED,
  STATUS_METHOD_NOT_ALLOWED,
  STATUS_MISDIRECTED_REQUEST,
  STATUS_MOVED_PERMANENTLY,
  STATUS_MULTIPLE_CHOICES,
  STATUS_NON_AUTHORITATIVE,
  STATUS_NOT_ACCEPTABLE,
  STATUS_NOT_FOUND,
  STATUS_NOT_IMPLEMENTED,
  STATUS_NOT_MODIFIED,
  STATUS_NO_CONTENT,
  STATUS_OK,
  STATUS_PARTIAL_CONTENT,
  STATUS_PAYMENT_REQUIRED,
  STATUS_PERMANENT_REDIRECT,
  STATUS_PRECONDITION_FAILED,
  STATUS_PROXY,
  STATUS_PROXY_AUTHENTICATION_REQUIRED,
  STATUS_RANGE_NOT_SPECIFIED,
  STATUS_REQUEST_TIMEOUT,
  STATUS_RESET_CONTENT,
  STATUS_SEE_OTHER,
  STATUS_SERVICE_UNVAILABLE,
  STATUS_SWITCHING_PROTOCOLS,
  STATUS_TEMPORARY_REDIRECT,
  STATUS_UNAUTHORIZED,
  STATUS_UNPROCESSABLE_CONTENT,
  STATUS_UNSUPPORTED_MEDIA_TYPE,
  STATUS_UNUSED,
  STATUS_UPGRADE_REQUIRED,
  STATUS_URI_TOO_LONG
}
